language: elixir
elixir:
  - 1.5.2
  - 1.4.5
sudo: false
env:
  - MIX_ENV=test
script:
  - mix do deps.get, coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
